#pragma once
// #include "esphome/components/ram_sensor/ram_sensor_int16.h"
// #include "esphome/components/adc/adc_sensor.h"
// #include "esphome/components/binary_sensor/automation.h"
// #include "esphome/components/binary_sensor/binary_sensor.h"
// #include "esphome/components/binary_sensor/filter.h"
// #include "esphome/components/dallas/dallas_component.h"
// #include "esphome/components/dallas/esp_one_wire.h"
// #include "esphome/components/display/display_buffer.h"
// #include "esphome/components/gpio/binary_sensor/gpio_binary_sensor.h"
// #include "esphome/components/gpio/switch/gpio_switch.h"
// #include "esphome/components/hx711/hx711.h"
// #include "esphome/components/json/json_util.h"
#include "esphome/components/logger/logger.h"
// #include "esphome/components/max7219/max7219.h"
// #include "esphome/components/mqtt/custom_mqtt_device.h"
// #include "esphome/components/mqtt/mqtt_binary_sensor.h"
// #include "esphome/components/mqtt/mqtt_client.h"
// #include "esphome/components/mqtt/mqtt_climate.h"
// #include "esphome/components/mqtt/mqtt_component.h"
// #include "esphome/components/mqtt/mqtt_cover.h"
// #include "esphome/components/mqtt/mqtt_fan.h"
// #include "esphome/components/mqtt/mqtt_light.h"
// #include "esphome/components/mqtt/mqtt_sensor.h"
// #include "esphome/components/mqtt/mqtt_switch.h"
// #include "esphome/components/mqtt/mqtt_text_sensor.h"
// #include "esphome/components/mqtt_subscribe/sensor/mqtt_subscribe_sensor.h"
// #include "esphome/components/pulse_counter/pulse_counter_sensor.h"
// #include "esphome/components/sensor/automation.h"
// #include "esphome/components/sensor/filter.h"
// #include "component/sensor.h"
// #include "esphome/components/spi/spi.h"
// #include "esphome/components/status_led/status_led.h"
// #include "esphome/components/switch/automation.h"
// #include "esphome/components/switch/switch.h"
// #include "esphome/components/template/binary_sensor/template_binary_sensor.h"
// #include "esphome/components/uptime/uptime_sensor.h"
// #include "esphome/components/voltage_sampler/voltage_sampler.h"
#include "esphome/components/wifi/wifi_component.h"
// #include "esphome/components/wifi_signal/wifi_signal_sensor.h"
#include "esphome/core/application.h"
#include "esphome/core/automation.h"
#include "esphome/core/base_automation.h"
#include "esphome/core/component.h"
#include "esphome/core/controller.h"
#include "esphome/core/defines.h"
#include "esphome/core/esphal.h"
#include "esphome/core/helpers.h"
#include "esphome/core/log.h"
#include "esphome/core/optional.h"
#include "esphome/core/preferences.h"
#include "esphome/core/scheduler.h"
#include "esphome/core/util.h"
#include "esphome/core/version.h"

